export const REQUEST_USER = "REQUEST_USER"
export const RESPONSE_USER= "RESPONSE_USER"

export const REQUEST_USERPREFS = "REQUEST_USERPREFS"
export const RESPONSE_USERPREFS = "RESPONSE_USERPREFS"

export const START_SAVEUSERPREFS = "START_SAVEUSERPREFS"
export const FINISH_SAVEUSERPREFS = "FINISH_SAVEUSERPREFS"

export const REQUEST_MESSAGECOUNT = "REQUEST_MESSAGECOUNT"
export const RESPONSE_MESSAGECOUNT = "RESPONSE_MESSAGECOUNT"