'use strict'

export const START_AUTHORIZE = "START_AUTHORIZE"
export const FINISH_AUTHORIZE = "FINISH_AUTHORIZE"

export const REQUEST_USER = "REQUEST_USER"
export const RESPONSE_USER = "RESPONSE_USER"

export const CLEAR_USER = "CLEAR_USER"

export const REQUEST_USERCOLLECT = "REQUEST_USERCOLLECT"
export const RESPONSE_USERCOLLECT = "RESPONSE_USERCOLLECT"