'use strict'

export const REQUEST_MESSAGES = "REQUEST_MESSAGES"
export const RESPONSE_MESSAGES = "RESPONSE_MESSAGES"

export const REQUEST_MESSAGECOUNT = "REQUEST_MESSAGECOUNT"
export const RESPONSE_MESSAGECOUNT = "RESPONSE_MESSAGECOUNT"

export const START_MARKALLMESSAGE = "START_MARKALLMESSAGE"
export const FINISH_MARKALLMESSAGE = "FINISH_MARKALLMESSAGE"