'use strict'

export const REQUEST_MESSAGES = "REQUEST_MESSAGES"
export const RESPONSE_MESSAGES = "RESPONSE_MESSAGES"


export const START_MARKALLMESSAGE = "START_MARKALLMESSAGE"
export const FINISH_MARKALLMESSAGE = "FINISH_MARKALLMESSAGE"