'use strict'

export const REQUEST_TOPICS = "REQUEST_TOPICS"
export const RESPONSE_TOPICS = "RESPONSE_TOPICS"

export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const FILTER_TOPICS = "FILTER_TOPICS"

export const REQUEST_TOPIC = "REQUEST_TOPIC"
export const RESPONSE_TOPIC = "RESPONSE_TOPIC"