'use strict'

export const REQUEST_TOPICS = "REQUEST_TOPICS"
export const RESPONSE_TOPICS = "RESPONSE_TOPICS"

export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const FILTER_TOPICS = "FILTER_TOPICS"

export const REQUEST_TOPIC = "REQUEST_TOPIC"
export const RESPONSE_TOPIC = "RESPONSE_TOPIC"

export const START_SAVEREPLY = "START_SAVEREPLY"
export const FINISH_SAVEREPLY = "FINISH_SAVEREPLY"

export const CHANGE_FIELD = "CHANGE_FIELD"
export const START_SAVETOPIC = "START_SAVETOPIC"
export const FINISH_SAVETOPIC = "FINISH_SAVETOPIC"

export const START_TOGGLECOLLECT = "START_TOGGLECOLLECT"
export const FINISH_TOGGLECOLLECT = "FINISH_TOGGLECOLLECT"

export const START_TOGGLEAGREE = "START_TOGGLEAGREE"
export const FINISH_TOGGLEAGREE = "FINISH_TOGGLEAGREE"