export default {
    header:{
        backgroundColor:"#444",
        borderBottomColor:"#000"
    },
    loading:{
        color:"#FFFFFF"
    },
    container:{
        backgroundColor:"#333"
    },
    navigationBarTitleText:{
        color:"#FFF"
    },
    navigationBarButtonText:{
        color:"#FFF"
    },
    searchBar:{
        backgroundColor:"#444",
        borderBottomColor:"#000"
    },
    searchBarButtonText:{
        color:"#FFF"
    },
    tabBar:{
        borderTopColor:"#000",
        backgroundColor:"#444"
    },
    tabBarItemText:{
        color:"#FFF"
    },
    tabBarSelectedItemText:{
        color:"dodgerblue"
    },
    tabs:{
        borderTopColor:"#000",
        backgroundColor:"#444"
    },
    loadMoreText:{
        color:"#999"
    }
}