export default {
    topicCell:{
        backgroundColor:"#333"
    },
    topicMintitleText:{
        color:"#999"
    },
    topicSubtitleText:{
        color:"#999"
    },
    cellSeparator:{
        backgroundColor:"#000"  
    },
    topicTag:{
        backgroundColor:"#555"  
    },
    topicTagText:{
        color:"#999"
    },
    cellSubtitleText:{
        color:"#999"
    },
    cellAccessory:{
        backgroundColor:"#555"
    },
    cellAccessoryText:{
        color:"#999"
    },
    topicReply:{
        color:"#999"
    },
    topicTitleText:{
        color:"#999"
    }
}