export const PUSH_SCENE = "PUSH_SCENE"
export const POP_SCENE = "POP_SCENE"
export const FOCUS_SCENE = "FOCUS_SCENE"
export const JUMPTO_SCENE = "JUMPTO_SCENE"
export const RESET_SCENE = "RESET_SCENE"
export const RELOAD_SCENE = "RELOAD_SCENE"