export const REQUEST_USER = "REQUEST_USER"
export const RESPONSE_USER = "RESPONSE_USER"

export const CLEAR_USER = "CLEAR_USER"

export const START_ERASECACHE = "START_ERASECACHE"
export const FINISH_ERASECACHE = "FINISH_ERASECACHE"